### ISSUE TITLE
Need a procedure to remove a puppet node 

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-Puppet#17]
This is important in the context of dynamic environments where the user may need to scale up and down the number of nodes based on demand. 

When scaling down, before terminating an instance we need to be able to remove the puppet node, revoke its certificate and free up the license that the node was using.

**Comment by chanijindal1** [comment]
In order to remove a node from master , the master needs to revoke and clean the certificate of that client/node .
"puppet cert clean <node> " does this job . 
ManageCertificatesAndRequests procedure can be used for the same .

Please refer to this link for a better understanding : https://ask.puppetlabs.com/question/842/how-to-delete-a-node-from-puppet/
